S2-F13
TerryIsmael/Acme-L3-D04 pull request #270
Opened 2023-05-22 18:01 UTC by virolialo

2023-05-22 18:49 UTC, rafgoncas1 requested changes

2023-05-22 18:49 UTC, rafgoncas1 commented on src/main/java/acme/features/authenticated/student/course/StudentCourseShowService.java
> +
comprobar que el rol es estudiante par ver cualquier curso

2023-05-22 18:49 UTC, rafgoncas1 commented on src/main/java/acme/features/authenticated/student/lecture/StudentLectureListService.java
> +
comprobar que el dato courseId está presente

2023-05-22 18:49 UTC, rafgoncas1 commented on src/main/java/acme/features/authenticated/student/lecture/StudentLectureListService.java
> +		if (super.getRequest().hasData("courseId", int.class)) {
si compruebas en el check que courseId está presente no necesitas este if

2023-05-22 18:49 UTC, rafgoncas1 commented on src/main/java/acme/features/authenticated/student/lecture/StudentLectureShowService.java
> +		super.getResponse().setAuthorised(true);
comprobar que es estudiante quizás?

2023-05-22 18:49 UTC, rafgoncas1 commented on src/main/java/acme/features/authenticated/student/lecturer/StudentLecturerShowService.java
> +		super.getResponse().setAuthorised(true);
comprobar que es estudiante quizás?

2023-05-22 21:14 UTC, virolialo commented on src/main/java/acme/features/authenticated/student/AuthenticatedStudentCreateService.java
> +		status = !super.getRequest().getPrincipal().hasRole(Student.class);
Fallo encontrado revisando los authorise

2023-05-22 21:15 UTC, virolialo commented on src/main/java/acme/features/authenticated/student/course/StudentCourseShowService.java
> +		final boolean student = super.getRequest().getPrincipal().hasRole(Student.class);
Condicion booleana que comprueba que es estudiante añadida

2023-05-22 21:16 UTC, virolialo commented on src/main/java/acme/features/authenticated/student/course/StudentCourseShowService.java
> +		status = course != null && student == true;
Operador AND para comprobar que además se cumple que es estudiante

2023-05-22 21:16 UTC, virolialo commented on src/main/java/acme/features/authenticated/student/lecture/StudentLectureListService.java
> +		super.getResponse().setChecked(check);
Comprobar que es estudiante

2023-05-22 21:17 UTC, virolialo commented on src/main/java/acme/features/authenticated/student/lecture/StudentLectureListService.java
> +		super.getResponse().setGlobal("courseId", courseId);
Condicion del if eliminada al comprobarlo en el check

2023-05-22 21:17 UTC, virolialo commented on src/main/java/acme/features/authenticated/student/lecture/StudentLectureShowService.java
> +		super.getResponse().setAuthorised(status);
Authorise arreglado

2023-05-23 10:49 UTC, rafgoncas1 approved these changes
Los cambios son correctos.

2023-05-23 10:52 UTC, merged